name: pytorch_ltr
channels:
  - defaults
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - python=3.10
  - pip
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - lightgbm
  - xgboost
  - notebook
  - jupyterlab
  - jupyter_contrib_nbextensions
  - ipykernel
  - pip:
    - ptranking